namespace NewDynamicFormGenAPI.Models.DTOs.Rules;

/// <summary>
/// Data transfer object representing a validation or conditional rule applied to a form control.
/// </summary>
/// <remarks>
/// <para>
/// FormRuleDto encapsulates a single rule instance with its configuration and metadata.
/// Rules are applied to controls to enforce validation constraints or conditionally alter form state.
/// </para>
/// <para>
/// Rule types include:
/// <list type="bullet">
///   <item><description>Validation rules - enforce data quality (Required, Length, Format, Pattern, Range)</description></item>
///   <item><description>Conditional rules - alter form state (Visibility, EnableDisable, RequiredOptional)</description></item>
/// </list>
/// </para>
/// <para>
/// See <see cref="Enums.RuleType"/> for the complete taxonomy of rule types.
/// </para>
/// </remarks>
public class FormRuleDto
{
    /// <summary>
    /// Gets or sets the unique identifier for this rule.
    /// </summary>
    /// <remarks>
    /// Rule IDs enable updating and deleting specific rules. They are typically generated as GUIDs
    /// and stored within the form definition JSON.
    /// </remarks>
    public string RuleId { get; set; } = "";

    /// <summary>
    /// Gets or sets the key of the control this rule is applied to.
    /// </summary>
    /// <remarks>
    /// The control key identifies which control on the form is subject to this rule.
    /// For conditional rules, this is the control being targeted for state change.
    /// </remarks>
    public string ControlKey { get; set; } = null!;

    /// <summary>
    /// Gets or sets the type of rule (Required, Length, Format, Visibility, etc.).
    /// </summary>
    /// <remarks>
    /// The rule type determines how the rule is interpreted and enforced.
    /// See <see cref="Enums.RuleType"/> for valid rule types.
    /// </remarks>
    public string RuleType { get; set; } = null!;

    /// <summary>
    /// Gets or sets rule-specific configuration as JSON.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The structure of this JSON varies by rule type. Examples:
    /// <list type="bullet">
    ///   <item><description>Length rule: <c>{"minLength": 5, "maxLength": 50}</c></description></item>
    ///   <item><description>Range rule: <c>{"min": 0, "max": 100}</c></description></item>
    ///   <item><description>Pattern rule: <c>{"pattern": "^[A-Z]{3}\\d{3}$"}</c></description></item>
    ///   <item><description>Visibility rule: <c>{"triggerControlKey": "status", "triggerValue": "active", "conditions": [...]}</c></description></item>
    /// </list>
    /// </para>
    /// </remarks>
    public string? RuleDetailsJson { get; set; }

    /// <summary>
    /// Gets or sets the error message to display when validation fails or for user guidance.
    /// </summary>
    /// <remarks>
    /// This message is shown to users when their input violates a validation rule.
    /// For conditional rules, this may be descriptive text about the rule's effects.
    /// </remarks>
    public string ErrorMessage { get; set; } = "";

    /// <summary>
    /// Gets or sets the severity level of this rule violation.
    /// </summary>
    /// <remarks>
    /// <list type="bullet">
    ///   <item><description>"Error" - Violation prevents form submission</description></item>
    ///   <item><description>"Warning" - Violation is reported but does not block submission</description></item>
    /// </list>
    /// See <see cref="Enums.RuleSeverity"/> for valid severity values.
    /// </remarks>
    public string Severity { get; set; } = "Error";

    /// <summary>
    /// Gets or sets the display order of this rule relative to other rules on the same control.
    /// </summary>
    /// <remarks>
    /// Rules are evaluated and displayed in ascending order of DisplayOrder.
    /// This affects message display order and validation sequence.
    /// </remarks>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this rule is currently active and should be enforced.
    /// </summary>
    /// <remarks>
    /// Inactive rules are not evaluated during validation or conditional logic processing,
    /// allowing rules to be disabled without deletion.
    /// </remarks>
    public bool IsActive { get; set; } = true;
}

/// <summary>
/// Data transfer object for creating or updating a rule on a form control.
/// </summary>
/// <remarks>
/// CreateFormRuleDto is used by API endpoints to accept rule creation and edit requests.
/// Unlike FormRuleDto, it does not include the RuleId (which is generated by the backend).
/// </remarks>
public class CreateFormRuleDto
{
    /// <summary>
    /// Gets or sets the key of the control this rule applies to.
    /// </summary>
    public string ControlKey { get; set; } = null!;

    /// <summary>
    /// Gets or sets the type of rule to create.
    /// </summary>
    /// <remarks>
    /// See <see cref="Enums.RuleType"/> for valid rule types.
    /// </remarks>
    public string RuleType { get; set; } = null!;

    /// <summary>
    /// Gets or sets rule-specific configuration as JSON.
    /// </summary>
    /// <remarks>
    /// The JSON structure depends on the RuleType. See FormRuleDto.RuleDetailsJson for examples.
    /// </remarks>
    public string? RuleDetailsJson { get; set; }

    /// <summary>
    /// Gets or sets the error message for validation failures or user guidance.
    /// </summary>
    public string ErrorMessage { get; set; } = null!;

    /// <summary>
    /// Gets or sets the severity level ("Error" or "Warning").
    /// </summary>
    public string Severity { get; set; } = "Error";

    /// <summary>
    /// Gets or sets the display order of this rule.
    /// </summary>
    public int DisplayOrder { get; set; }
}

/// <summary>
/// Defines how multiple conditions on a single rule are combined for evaluation.
/// </summary>
/// <remarks>
/// <para>
/// When a rule has multiple conditions (e.g., "Show control X if control Y = 'value1' AND control Z = 'value2'"),
/// this constant specifies how those conditions are logically combined.
/// </para>
/// </remarks>
public static class ConditionLogic
{
    /// <summary>
    /// Condition logic: all conditions must be true for the rule to trigger.
    /// </summary>
    public const string And = "AND";

    /// <summary>
    /// Condition logic: at least one condition must be true for the rule to trigger.
    /// </summary>
    public const string Or = "OR";
}
